<?php

declare(strict_types=1);

namespace Xmon\AiContentBundle\DependencyInjection;

use Symfony\Component\Config\Definition\Builder\TreeBuilder;
use Symfony\Component\Config\Definition\ConfigurationInterface;

class Configuration implements ConfigurationInterface
{
    public function getConfigTreeBuilder(): TreeBuilder
    {
        $treeBuilder = new TreeBuilder('xmon_ai_content');
        $rootNode = $treeBuilder->getRootNode();

        $rootNode
            ->children()
                // Task-specific model configuration
                ->arrayNode('tasks')
                    ->addDefaultsIfNotSet()
                    ->info('Configure models per task. Query available: curl -H "Authorization: Bearer KEY" https://gen.pollinations.ai/models')
                    ->children()
                        ->arrayNode('news_content')
                            ->addDefaultsIfNotSet()
                            ->info('Models for generating news article content')
                            ->children()
                                ->scalarNode('default_model')
                                    ->defaultValue('gemini')
                                    ->info('Default model (gemini = seed tier, good quality)')
                                ->end()
                                ->arrayNode('allowed_models')
                                    ->scalarPrototype()->end()
                                    ->defaultValue(['gemini', 'deepseek', 'mistral', 'openai', 'openai-fast'])
                                    ->info('Models allowed for this task')
                                ->end()
                            ->end()
                        ->end()
                        ->arrayNode('image_prompt')
                            ->addDefaultsIfNotSet()
                            ->info('Models for generating image descriptions/prompts')
                            ->children()
                                ->scalarNode('default_model')
                                    ->defaultValue('gemini-fast')
                                    ->info('Default model (gemini-fast = seed tier, fast & cheap)')
                                ->end()
                                ->arrayNode('allowed_models')
                                    ->scalarPrototype()->end()
                                    ->defaultValue(['gemini-fast', 'openai-fast', 'mistral', 'openai'])
                                    ->info('Models allowed for this task')
                                ->end()
                            ->end()
                        ->end()
                        ->arrayNode('image_generation')
                            ->addDefaultsIfNotSet()
                            ->info('Models for generating images')
                            ->children()
                                ->scalarNode('default_model')
                                    ->defaultValue('flux')
                                    ->info('Default model (flux = anonymous tier, free & good quality)')
                                ->end()
                                ->arrayNode('allowed_models')
                                    ->scalarPrototype()->end()
                                    ->defaultValue(['flux', 'turbo'])
                                    ->info('Models allowed for this task')
                                ->end()
                            ->end()
                        ->end()
                    ->end()
                ->end()
                // Text generation configuration (Pollinations provider)
                ->arrayNode('text')
                    ->addDefaultsIfNotSet()
                    ->info('Text generation via Pollinations API')
                    ->children()
                        ->scalarNode('api_key')
                            ->defaultNull()
                            ->info('Pollinations API key (optional, removes rate limits)')
                        ->end()
                        ->scalarNode('model')
                            ->defaultValue('mistral')
                            ->info('Default text model (free tier)')
                        ->end()
                        ->arrayNode('fallback_models')
                            ->scalarPrototype()->end()
                            ->defaultValue(['nova-micro', 'gemini-fast', 'openai-fast'])
                            ->info('Models to try if primary fails (free tier)')
                        ->end()
                        ->integerNode('retries_per_model')
                            ->defaultValue(2)
                            ->min(1)
                            ->max(10)
                            ->info('Retries before trying next model')
                        ->end()
                        ->integerNode('retry_delay')
                            ->defaultValue(3)
                            ->min(0)
                            ->max(60)
                            ->info('Seconds between retries')
                        ->end()
                        ->integerNode('timeout')
                            ->defaultValue(60)
                            ->info('HTTP timeout in seconds')
                        ->end()
                        ->enumNode('endpoint_mode')
                            ->values(['simple', 'openai'])
                            ->defaultValue('openai')
                            ->info('Endpoint mode: "simple" (GET) or "openai" (POST /v1/chat/completions)')
                        ->end()
                    ->end()
                ->end()
                // Image generation configuration (Pollinations provider)
                ->arrayNode('image')
                    ->addDefaultsIfNotSet()
                    ->info('Image generation via Pollinations API')
                    ->children()
                        ->scalarNode('api_key')
                            ->defaultNull()
                            ->info('Pollinations API key (optional, unlocks premium models)')
                        ->end()
                        ->scalarNode('model')
                            ->defaultValue('flux')
                            ->info('Default image model (free tier)')
                        ->end()
                        ->arrayNode('fallback_models')
                            ->scalarPrototype()->end()
                            ->defaultValue(['zimage', 'turbo'])
                            ->info('Models to try if primary fails (free tier)')
                        ->end()
                        ->integerNode('retries_per_model')
                            ->defaultValue(2)
                            ->min(1)
                            ->max(10)
                            ->info('Retries before trying next model')
                        ->end()
                        ->integerNode('retry_delay')
                            ->defaultValue(3)
                            ->min(0)
                            ->max(60)
                            ->info('Seconds between retries')
                        ->end()
                        ->integerNode('timeout')
                            ->defaultValue(120)
                            ->info('HTTP timeout in seconds')
                        ->end()
                        ->integerNode('width')
                            ->defaultValue(1280)
                            ->info('Default image width')
                        ->end()
                        ->integerNode('height')
                            ->defaultValue(720)
                            ->info('Default image height')
                        ->end()
                        ->enumNode('quality')
                            ->values(['low', 'medium', 'high', 'hd'])
                            ->defaultValue('high')
                            ->info('Image quality level')
                        ->end()
                        ->scalarNode('negative_prompt')
                            ->defaultValue('worst quality, blurry, text, letters, watermark, human faces, detailed faces')
                            ->info('What to avoid in generated images')
                        ->end()
                        ->booleanNode('private')
                            ->defaultTrue()
                            ->info('Hide images from Pollinations public feeds')
                        ->end()
                        ->booleanNode('nofeed')
                            ->defaultTrue()
                            ->info('Do not add images to public feed')
                        ->end()
                    ->end()
                ->end()
                // SonataMedia integration
                ->arrayNode('media')
                    ->addDefaultsIfNotSet()
                    ->children()
                        ->scalarNode('default_context')->defaultValue('default')->end()
                        ->scalarNode('provider')->defaultValue('sonata.media.provider.image')->end()
                    ->end()
                ->end()
                // Sonata Admin integration
                ->arrayNode('admin')
                    ->addDefaultsIfNotSet()
                    ->children()
                        ->scalarNode('base_template')
                            ->defaultValue('@SonataAdmin/standard_layout.html.twig')
                            ->info('Base template to extend for admin pages. Override to use your project\'s custom admin layout.')
                        ->end()
                        ->booleanNode('show_bundle_credit')
                            ->defaultTrue()
                            ->info('Show "Powered by XmonAiContentBundle" footer in the AI image generation page.')
                        ->end()
                    ->end()
                ->end()
                // Image options: styles, compositions, palettes, extras
                ->arrayNode('image_options')
                    ->addDefaultsIfNotSet()
                    ->children()
                        // Disable specific bundle defaults
                        ->arrayNode('disable_defaults')
                            ->addDefaultsIfNotSet()
                            ->children()
                                ->arrayNode('styles')
                                    ->scalarPrototype()->end()
                                    ->defaultValue([])
                                ->end()
                                ->arrayNode('compositions')
                                    ->scalarPrototype()->end()
                                    ->defaultValue([])
                                ->end()
                                ->arrayNode('palettes')
                                    ->scalarPrototype()->end()
                                    ->defaultValue([])
                                ->end()
                                ->arrayNode('extras')
                                    ->scalarPrototype()->end()
                                    ->defaultValue([])
                                ->end()
                            ->end()
                        ->end()
                        // Artistic styles (merged with bundle defaults)
                        ->arrayNode('styles')
                            ->useAttributeAsKey('key')
                            ->normalizeKeys(false)
                            ->arrayPrototype()
                                ->children()
                                    ->scalarNode('label')->isRequired()->end()
                                    ->scalarNode('prompt')->isRequired()->end()
                                    ->scalarNode('group')->defaultNull()->end()
                                ->end()
                            ->end()
                        ->end()
                        // Compositions (merged with bundle defaults)
                        ->arrayNode('compositions')
                            ->useAttributeAsKey('key')
                            ->normalizeKeys(false)
                            ->arrayPrototype()
                                ->children()
                                    ->scalarNode('label')->isRequired()->end()
                                    ->scalarNode('prompt')->isRequired()->end()
                                    ->scalarNode('group')->defaultNull()->end()
                                ->end()
                            ->end()
                        ->end()
                        // Color palettes (merged with bundle defaults)
                        ->arrayNode('palettes')
                            ->useAttributeAsKey('key')
                            ->normalizeKeys(false)
                            ->arrayPrototype()
                                ->children()
                                    ->scalarNode('label')->isRequired()->end()
                                    ->scalarNode('prompt')->isRequired()->end()
                                    ->scalarNode('group')->defaultNull()->end()
                                ->end()
                            ->end()
                        ->end()
                        // Extra modifiers (merged with bundle defaults)
                        ->arrayNode('extras')
                            ->useAttributeAsKey('key')
                            ->normalizeKeys(false)
                            ->arrayPrototype()
                                ->children()
                                    ->scalarNode('label')->isRequired()->end()
                                    ->scalarNode('prompt')->isRequired()->end()
                                    ->scalarNode('group')->defaultNull()->end()
                                ->end()
                            ->end()
                        ->end()
                    ->end()
                ->end()
                // Presets: predefined combinations of options (merged with bundle defaults)
                ->arrayNode('presets')
                    ->useAttributeAsKey('key')
                    ->normalizeKeys(false)
                    ->arrayPrototype()
                        ->children()
                            ->scalarNode('name')->isRequired()->end()
                            ->scalarNode('style')->defaultNull()->end()
                            ->scalarNode('composition')->defaultNull()->end()
                            ->scalarNode('palette')->defaultNull()->end()
                            ->arrayNode('extras')
                                ->scalarPrototype()->end()
                                ->defaultValue([])
                            ->end()
                        ->end()
                    ->end()
                ->end()
                // Disable specific bundle preset defaults
                ->arrayNode('disable_preset_defaults')
                    ->scalarPrototype()->end()
                    ->defaultValue([])
                ->end()
                // Default preset when none is selected in admin
                ->scalarNode('default_preset')
                    ->defaultNull()
                    ->info('Preset to use as fallback when no preset is configured. If null, uses first available preset.')
                ->end()
                // Fixed suffix appended to all generated styles
                ->scalarNode('style_suffix')
                    ->defaultValue('')
                    ->info('Fixed text appended to all generated style prompts (e.g., quality modifiers, technical restrictions).')
                ->end()
                // Configurable prompt templates
                ->arrayNode('prompts')
                    ->addDefaultsIfNotSet()
                    ->children()
                        // Disable specific bundle prompt defaults
                        ->arrayNode('disable_defaults')
                            ->scalarPrototype()->end()
                            ->defaultValue([])
                        ->end()
                        // Custom prompts (merged with bundle defaults)
                        ->arrayNode('templates')
                            ->useAttributeAsKey('key')
                            ->normalizeKeys(false)
                            ->arrayPrototype()
                                ->children()
                                    ->scalarNode('name')->isRequired()->end()
                                    ->scalarNode('description')->defaultNull()->end()
                                    ->scalarNode('system')->isRequired()->end()
                                    ->scalarNode('user')->isRequired()->end()
                                    // Variant options for dynamic prompt injection
                                    ->arrayNode('variants')
                                        ->useAttributeAsKey('category')
                                        ->normalizeKeys(false)
                                        ->arrayPrototype()
                                            ->scalarPrototype()->end()
                                        ->end()
                                    ->end()
                                    // Keywords for intelligent variant matching (optional)
                                    // Keywords should be in the same language as the variant options
                                    ->arrayNode('variant_keywords')
                                        ->useAttributeAsKey('category')
                                        ->normalizeKeys(false)
                                        ->arrayPrototype()
                                            ->scalarPrototype()->end()
                                        ->end()
                                    ->end()
                                ->end()
                            ->end()
                        ->end()
                    ->end()
                ->end()
                // History settings
                ->arrayNode('history')
                    ->addDefaultsIfNotSet()
                    ->children()
                        ->integerNode('max_images')
                            ->defaultValue(5)
                            ->min(1)
                            ->max(50)
                            ->info('Maximum images to keep in history per entity')
                        ->end()
                    ->end()
                ->end()
                // Image subject generation (two-step anchor system)
                ->arrayNode('image_subject')
                    ->addDefaultsIfNotSet()
                    ->info('Two-step image subject generation with anchor extraction')
                    ->children()
                        // Anchor types and their visual guidelines
                        ->arrayNode('anchor_types')
                            ->useAttributeAsKey('type')
                            ->normalizeKeys(false)
                            ->scalarPrototype()->end()
                            ->info('Visual guidelines for each anchor type. Keys: PLACE, PERSON, NUMBER, EVENT, ORGANIZATION, MEMORIAL, default')
                        ->end()
                    ->end()
                ->end()
            ->end();

        return $treeBuilder;
    }
}
