<?php

declare(strict_types=1);

namespace Xmon\AiContentBundle\DependencyInjection;

use Symfony\Component\Config\Definition\Builder\TreeBuilder;
use Symfony\Component\Config\Definition\ConfigurationInterface;

class Configuration implements ConfigurationInterface
{
    public function getConfigTreeBuilder(): TreeBuilder
    {
        $treeBuilder = new TreeBuilder('xmon_ai_content');
        $rootNode = $treeBuilder->getRootNode();

        $rootNode
            ->children()
                // Text providers configuration
                // Unified schema: all providers use the same fields
                ->arrayNode('text')
                    ->addDefaultsIfNotSet()
                    ->children()
                        ->arrayNode('providers')
                            ->useAttributeAsKey('name')
                            ->arrayPrototype()
                                ->children()
                                    ->booleanNode('enabled')->defaultTrue()->end()
                                    ->integerNode('priority')->defaultValue(50)->end()
                                    ->scalarNode('api_key')->defaultNull()->end()
                                    ->scalarNode('model')->defaultNull()->end()
                                    ->arrayNode('fallback_models')
                                        ->scalarPrototype()->end()
                                        ->defaultValue([])
                                    ->end()
                                    ->integerNode('timeout')->defaultValue(30)->end()
                                ->end()
                            ->end()
                        ->end()
                        ->arrayNode('defaults')
                            ->addDefaultsIfNotSet()
                            ->children()
                                ->integerNode('retries')->defaultValue(2)->end()
                                ->integerNode('retry_delay')->defaultValue(3)->end()
                            ->end()
                        ->end()
                    ->end()
                ->end()
                // Image providers configuration
                ->arrayNode('image')
                    ->addDefaultsIfNotSet()
                    ->children()
                        ->arrayNode('providers')
                            ->useAttributeAsKey('name')
                            ->arrayPrototype()
                                ->children()
                                    ->booleanNode('enabled')->defaultTrue()->end()
                                    ->integerNode('priority')->defaultValue(1)->end()
                                    ->scalarNode('api_key')->defaultNull()->end()
                                    ->scalarNode('model')->defaultNull()->end()
                                    ->integerNode('timeout')->defaultValue(120)->end()
                                ->end()
                            ->end()
                        ->end()
                        ->arrayNode('defaults')
                            ->addDefaultsIfNotSet()
                            ->children()
                                ->integerNode('width')->defaultValue(1280)->end()
                                ->integerNode('height')->defaultValue(720)->end()
                                ->integerNode('retries')->defaultValue(3)->end()
                                ->integerNode('retry_delay')->defaultValue(5)->end()
                            ->end()
                        ->end()
                    ->end()
                ->end()
                // SonataMedia integration
                ->arrayNode('media')
                    ->addDefaultsIfNotSet()
                    ->children()
                        ->scalarNode('default_context')->defaultValue('default')->end()
                        ->scalarNode('provider')->defaultValue('sonata.media.provider.image')->end()
                    ->end()
                ->end()
                // Sonata Admin integration
                ->arrayNode('admin')
                    ->addDefaultsIfNotSet()
                    ->children()
                        ->scalarNode('base_template')
                            ->defaultValue('@SonataAdmin/standard_layout.html.twig')
                            ->info('Base template to extend for admin pages. Override to use your project\'s custom admin layout.')
                        ->end()
                        ->booleanNode('show_bundle_credit')
                            ->defaultTrue()
                            ->info('Show "Powered by XmonAiContentBundle" footer in the AI image generation page.')
                        ->end()
                    ->end()
                ->end()
                // Image options: styles, compositions, palettes, extras
                ->arrayNode('image_options')
                    ->addDefaultsIfNotSet()
                    ->children()
                        // Disable specific bundle defaults
                        ->arrayNode('disable_defaults')
                            ->addDefaultsIfNotSet()
                            ->children()
                                ->arrayNode('styles')
                                    ->scalarPrototype()->end()
                                    ->defaultValue([])
                                ->end()
                                ->arrayNode('compositions')
                                    ->scalarPrototype()->end()
                                    ->defaultValue([])
                                ->end()
                                ->arrayNode('palettes')
                                    ->scalarPrototype()->end()
                                    ->defaultValue([])
                                ->end()
                                ->arrayNode('extras')
                                    ->scalarPrototype()->end()
                                    ->defaultValue([])
                                ->end()
                            ->end()
                        ->end()
                        // Artistic styles (merged with bundle defaults)
                        ->arrayNode('styles')
                            ->useAttributeAsKey('key')
                            ->normalizeKeys(false)
                            ->arrayPrototype()
                                ->children()
                                    ->scalarNode('label')->isRequired()->end()
                                    ->scalarNode('prompt')->isRequired()->end()
                                    ->scalarNode('group')->defaultNull()->end()
                                ->end()
                            ->end()
                        ->end()
                        // Compositions (merged with bundle defaults)
                        ->arrayNode('compositions')
                            ->useAttributeAsKey('key')
                            ->normalizeKeys(false)
                            ->arrayPrototype()
                                ->children()
                                    ->scalarNode('label')->isRequired()->end()
                                    ->scalarNode('prompt')->isRequired()->end()
                                    ->scalarNode('group')->defaultNull()->end()
                                ->end()
                            ->end()
                        ->end()
                        // Color palettes (merged with bundle defaults)
                        ->arrayNode('palettes')
                            ->useAttributeAsKey('key')
                            ->normalizeKeys(false)
                            ->arrayPrototype()
                                ->children()
                                    ->scalarNode('label')->isRequired()->end()
                                    ->scalarNode('prompt')->isRequired()->end()
                                    ->scalarNode('group')->defaultNull()->end()
                                ->end()
                            ->end()
                        ->end()
                        // Extra modifiers (merged with bundle defaults)
                        ->arrayNode('extras')
                            ->useAttributeAsKey('key')
                            ->normalizeKeys(false)
                            ->arrayPrototype()
                                ->children()
                                    ->scalarNode('label')->isRequired()->end()
                                    ->scalarNode('prompt')->isRequired()->end()
                                    ->scalarNode('group')->defaultNull()->end()
                                ->end()
                            ->end()
                        ->end()
                    ->end()
                ->end()
                // Presets: predefined combinations of options (merged with bundle defaults)
                ->arrayNode('presets')
                    ->useAttributeAsKey('key')
                    ->normalizeKeys(false)
                    ->arrayPrototype()
                        ->children()
                            ->scalarNode('name')->isRequired()->end()
                            ->scalarNode('style')->defaultNull()->end()
                            ->scalarNode('composition')->defaultNull()->end()
                            ->scalarNode('palette')->defaultNull()->end()
                            ->arrayNode('extras')
                                ->scalarPrototype()->end()
                                ->defaultValue([])
                            ->end()
                        ->end()
                    ->end()
                ->end()
                // Disable specific bundle preset defaults
                ->arrayNode('disable_preset_defaults')
                    ->scalarPrototype()->end()
                    ->defaultValue([])
                ->end()
                // Configurable prompt templates
                ->arrayNode('prompts')
                    ->addDefaultsIfNotSet()
                    ->children()
                        // Disable specific bundle prompt defaults
                        ->arrayNode('disable_defaults')
                            ->scalarPrototype()->end()
                            ->defaultValue([])
                        ->end()
                        // Custom prompts (merged with bundle defaults)
                        ->arrayNode('templates')
                            ->useAttributeAsKey('key')
                            ->normalizeKeys(false)
                            ->arrayPrototype()
                                ->children()
                                    ->scalarNode('name')->isRequired()->end()
                                    ->scalarNode('description')->defaultNull()->end()
                                    ->scalarNode('system')->isRequired()->end()
                                    ->scalarNode('user')->isRequired()->end()
                                    // Variant options for dynamic prompt injection
                                    ->arrayNode('variants')
                                        ->useAttributeAsKey('category')
                                        ->normalizeKeys(false)
                                        ->arrayPrototype()
                                            ->scalarPrototype()->end()
                                        ->end()
                                    ->end()
                                    // Keywords for intelligent variant matching (optional)
                                    // Keywords should be in the same language as the variant options
                                    ->arrayNode('variant_keywords')
                                        ->useAttributeAsKey('category')
                                        ->normalizeKeys(false)
                                        ->arrayPrototype()
                                            ->scalarPrototype()->end()
                                        ->end()
                                    ->end()
                                ->end()
                            ->end()
                        ->end()
                    ->end()
                ->end()
                // History settings
                ->arrayNode('history')
                    ->addDefaultsIfNotSet()
                    ->children()
                        ->integerNode('max_images')
                            ->defaultValue(5)
                            ->min(1)
                            ->max(50)
                            ->info('Maximum images to keep in history per entity')
                        ->end()
                    ->end()
                ->end()
            ->end();

        return $treeBuilder;
    }
}
